In [1]:
import csv
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import cross_val_score, GridSearchCV, cross_validate, train_test_split
from sklearn.metrics import accuracy_score, classification_report
from sklearn.svm import SVC

# ML models
from sklearn.linear_model import LinearRegression
from sklearn.neural_network import MLPClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import PolynomialFeatures
from sklearn.neighbors import KNeighborsClassifier

# Save ML model as .pickle
import pickle
from sklearn.externals import joblib
# Implemented by Yikai Zhang (yzhang3488)

/Users/ikchang/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/__init__.py:15: DeprecationWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=DeprecationWarning)


In [2]:
knn_class = 150
po_deg = 3

In [3]:
df = pd.read_csv("output1.csv")
data0 = df.values.tolist()

In [4]:
len(data0)

21336

In [5]:
c = 0
d = 0
e = 0
for i in range(len(data0)):
    if data0[i][1] > 2000:
        c = c+1
        #print(data[i][1])
        if data0[i][1] > 5000:
            d = d+1
            if data0[i][1] > 20000:
                e = e+1
print(c)
print(d)
print(e)

3820
283
138


In [6]:
data0

[['5642 Windwood Rd, Atlanta, GA',
  950,
  627,
  3,
  2.5,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  1254,
  3,
  3.0,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  1232,
  2,
  3.0,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  638,
  2,
  2.5,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  638,
  2,
  2.5,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  1232,
  2,
  2.5,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  627,
  1,
  2.5,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['5642 Windwood Rd, Atlanta, GA',
  950,
  627,
  3,
  2.5,
  33.600359999999995,
  -84.419296,
  'Clayton County'],
 ['8229 Queens Dr, Atlanta, GA',
  1475,
  1939,
  3,

In [7]:
# exclude data that is too extreme
data = []
for i in range(len(data0)):
    if data0[i][1] < 20000:
        data.append(data0[i])
print(len(data))
# ...Or not. Atually it makes little difference
df = pd.read_csv("output1.csv")
data0 = df.values.tolist()

21198


In [8]:
# define x and y data
x_data = []
y_data = []
all_data = []
for i in range (len(data)):
    # X format: longitude, latitude, area, bedrooms, bathrooms
    # Y format: price
    x_data.append([data[i][5], data[i][6], data[i][2], data[i][3], data[i][4]])
    y_data.append(data[i][1])
    all_data.append([data[i][5], data[i][6], data[i][2], data[i][3], data[i][4], data[i][1]])

In [9]:
# rescale latitude and longitude (if necessary)

# 1. find mean latitude ad longitude
#mean_la = 0
#mean_lo = 0
#for i in range (len(x_data)):
#    mean_la = mean_la + x_data[i][0]
#    mean_lo = mean_lo + x_data[i][1]

#mean_la = mean_la / len(x_data)
#mean_lo = mean_lo / len(x_data)
#print(mean_la)
#print(mean_lo)
mean_la = 33
mean_lo = -84
# 2. rescale latitude and longitude
# define scale
scl = 1000000000
for i in range (len(x_data)):
    x_data[i][0] = (x_data[i][0] - mean_la) * scl
    x_data[i][1] = (x_data[i][1] - mean_lo) * scl

In [10]:
# split data into train and test
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size = 0.3, shuffle = True)

In [11]:
# find the range of the data
max_feature = [0,0,0,0,0,0]
min_feature = [100, 100, 100, 100, 100, 1000]
for i in range (len(data)):
    #print(i)
    for j in range (len(max_feature)):
        #find maximum
        if all_data[i][j] > max_feature[j]:
            max_feature[j] = all_data[i][j]
        #find manimum
        if all_data[i][j] < min_feature[j]:
            min_feature[j] = all_data[i][j]
print(min_feature)
print(max_feature)

[33.4017439, -122.47357050000001, 1, 0, 0.5, 500]
[48.7716808, 0, 26136, 21, 12.0, 9000]


In [12]:
"""
# MODEL #1: Linear Regression

# NOTE: ABANDOMED
model_LR = LinearRegression()
model_LR.fit(x_train, y_train)
"""

'\n# MODEL #1: Linear Regression\n\n# NOTE: ABANDOMED\nmodel_LR = LinearRegression()\nmodel_LR.fit(x_train, y_train)\n'

In [13]:
"""
# NOTE: ABANDOMED
yLR_train = model_LR.predict(x_train)
for i in range(len(yLR_train)):
    
    if yLR_train[i] < 0.5:
        yLR_train[i] = 0
    else:
        yLR_train[i] = 1

print(accuracy_score(yLR_train, y_train))
"""

'\n# NOTE: ABANDOMED\nyLR_train = model_LR.predict(x_train)\nfor i in range(len(yLR_train)):\n    \n    if yLR_train[i] < 0.5:\n        yLR_train[i] = 0\n    else:\n        yLR_train[i] = 1\n\nprint(accuracy_score(yLR_train, y_train))\n'

In [14]:
# MODEL #1: Linear Regression

# NOTE: pretty bad
model_LR = LinearRegression()
model_LR.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [15]:
# MODEL #2: KNN
neigh = KNeighborsClassifier(n_neighbors=knn_class)
neigh.fit(x_train, y_train)

# make prediction
y_final = neigh.predict(x_train)

# print predict result
l = 301
print(y_test[l])
print(neigh.predict(x_test)[l])

1050
1395


In [16]:
# MODEL #3: Polynomial Regression
poly = PolynomialFeatures(degree = po_deg) 
X_poly = poly.fit_transform(x_train)

poly.fit(X_poly, y_train) 
lin2 = LinearRegression() 
lin2.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [17]:
# print predict result
l = -200
print(y_test[l])
print(neigh.predict(x_test)[l])

1450
1295


In [18]:
# See if we stray the features too far from expected
t = [[33.864799600000005, -84.4718161, 1363, 10, 4.0],[33.864799600000005, -43.4718161, 1363, 2, 2.0]]
neigh.predict(t)

array([1625, 1625])

In [19]:
t = [33.864799600000005, -81.4718161, 1360, 10, 4.0]
m = neigh.predict([t])[0]
m

1625

In [20]:
l = 150
print(neigh.predict(x_test)[l])
print(y_test[l])

1750
1750


In [21]:
# Save the trained model as a pickle string.
saved_model = pickle.dumps(neigh)
joblib.dump(neigh, 'knnmodel150_g.pkl')
# Save the trained model as a pickle string.
saved_model2 = pickle.dumps(model_LR)
joblib.dump(neigh, 'lrmodel_g.pkl')

['lrmodel_g.pkl']

In [22]:
# calculate output models
y_knn = neigh.predict(x_test)
y_lr = model_LR.predict(x_test)
y_poly = lin2.predict(poly.fit_transform(x_test)) 

In [23]:
def cust_mean_error(a, b):
    diff = []
    out = 0
    for i in range(len(a)):
        diff.append(a[i] - b[i])
        #squared error
        diff[i] = abs(diff[i])# * diff[i]
    
    # take mean value of the square
    out = sum(diff) / len(a)
    
    return  out

In [24]:
mean_knn = cust_mean_error(y_knn, y_test)
mean_lr = cust_mean_error(y_lr, y_test)
mean_poly = cust_mean_error(y_poly, y_test)

In [25]:
print(mean_knn)
print(mean_lr)
print(mean_poly)

432.82924528301885
376.83354304254294
358.58365023081575


In [26]:
mse_knn = np.square(np.subtract(y_knn, y_test)).mean() 
mse_lr = np.square(np.subtract(y_lr, y_test)).mean()
mse_poly = np.square(np.subtract(y_poly, y_test)).mean() 

In [27]:
print(mse_knn)
print(mse_lr)
print(mse_poly)

645687.5534591195
382208.99390391784
340372.4698955325


In [28]:
y_knn

array([1736, 1250, 1660, ..., 1395, 1835, 1700])

In [29]:
y_lr

array([1772.19349868, 1702.05378436, 1907.59248483, ..., 1574.1130735 ,
       1846.7680468 , 1932.74625239])

In [30]:
y_poly

array([1857.78878193, 1749.88103181, 1736.23620259, ..., 1495.7193827 ,
       1718.82242547, 2143.4196908 ])

In [31]:
y_test

[1736,
 1100,
 1675,
 1525,
 2045,
 1675,
 1250,
 2400,
 1195,
 1295,
 1645,
 2000,
 2445,
 1000,
 1750,
 1250,
 2075,
 4200,
 1200,
 1675,
 1695,
 1490,
 2200,
 1800,
 1625,
 1695,
 1395,
 1500,
 1650,
 1000,
 4000,
 1250,
 2450,
 1605,
 1900,
 1700,
 2795,
 2015,
 1750,
 1300,
 1695,
 1295,
 1250,
 1150,
 1477,
 1250,
 1258,
 1349,
 1200,
 2100,
 2000,
 2990,
 1445,
 1525,
 2195,
 1495,
 2350,
 2400,
 1200,
 1750,
 1605,
 2500,
 1250,
 1645,
 1585,
 850,
 1385,
 1535,
 1545,
 1425,
 1499,
 1800,
 1895,
 1500,
 1250,
 950,
 1300,
 1500,
 1945,
 3995,
 1695,
 2300,
 1695,
 595,
 1325,
 1100,
 1850,
 1490,
 1625,
 2000,
 1340,
 1495,
 1595,
 2195,
 2995,
 1337,
 1495,
 2100,
 1500,
 1395,
 2300,
 1477,
 1150,
 1612,
 1300,
 1821,
 2100,
 1950,
 2250,
 1750,
 2200,
 1650,
 1600,
 1595,
 1600,
 1683,
 1620,
 2100,
 1425,
 1500,
 920,
 4700,
 1400,
 1288,
 1279,
 1345,
 1400,
 1595,
 2100,
 2000,
 1500,
 1400,
 1450,
 1225,
 640,
 1395,
 2200,
 1850,
 1720,
 1350,
 1795,
 1449,
 2350,
 132

In [32]:
y_test[-1]

2300

In [33]:
# See if we stray the features too far from expected
t = [[33.864799600000005, -84.4718161, 1363, 4, 4.0],[33.864799600000005, -84.9718161, 1363, 4, 4.0]]
for i in range(len(t)):
    t[i][0] = (t[i][0] - mean_la) * scl
    t[i][1] = (t[i][1] - mean_lo) * scl
print(neigh.predict(t))
print(model_LR.predict(t))

[2250 1699]
[1815.01364956 1807.83035074]
